# Generated by Django 4.2.1 on 2023-06-08 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('age', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('elo', models.EmailField(max_length=100, verbose_name='Эло')),
                ('hours', models.CharField(max_length=100, verbose_name='Часы')),
                ('discord', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Дискорд')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-Я- ]+$', message='Разрешена только кириллица')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rules',
            field=models.CharField(blank=True, max_length=100, verbose_name='Правила'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-Я- ]+$', message='Разрешена только кириллица')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]+$', message='Разрешена только латиница')], verbose_name='Логин'),
        ),
    ]
